version: "3"
services:
  api:
    container_name: ac-movie-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4211:4211
    volumes:
      - ./api:/usr/src/api
    restart: always
    links:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TMDB_API_KEY: ${TMDB_API_KEY}
      DATABASE_URL: ${DATABASE_URL}

  app:
    container_name: ac-movie-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 4212:4212
    volumes:
      - ./app:/usr/src/app
    restart: always
    links:
      - api

  postgres:
    image: postgres
    container_name: ${POSTGRES_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres
